### ISSUE TITLE
Create Class Diagram for #4

### ISSUE THREAD

**Issue by parvezpatel30** [appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin#10]

**Comment by appsmehta** [comment]
Hey @parvezpatel30 , Let me know if we are good with this and if anything else is needed to implement #11 in Greenfoot!

**Comment by appsmehta** [comment]
here's the commit link

https://github.com/appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin/blob/master/PeruvianClassDiagram.png

**Comment by parvezpatel30** [comment]
Hey @appsmehta , looking at the class diagram, I am thinking do we need to create separate interfaces?

**Comment by appsmehta** [comment]
@parvezpatel30  nope I don't think it's required, since only place I see this is for player objects and all our objects on the canvas would be extending the actor class in greenfoot.

**Comment by parvezpatel30** [comment]
Hey @appsmehta : Shouldn't class captain be a subclass of the class player? As essentially, Captain "is a" Player after all.

**Comment by appsmehta** [comment]
@parvezpatel30  Agree, I was not making Captain a subclass of Player just because I wanted Captain to be different from rest of the teammates. Since other teammates can't contact the Rival team captain directly, so any requests have to be routed through their captain. 

Now that I think of it, Player Parent and Captain child makes more sense. In case we feel the need for a second child, we can name it "Teammate". 

Any thoughts @pavanshah77 @vjzaveri @yugalk14

**Comment by parvezpatel30** [comment]
Yes @appsmehta

"Since other teammates can't contact the Rival team captain directly, so any requests have to be routed through their captain."
- Captain class can extend the Player class and then add its own method "contactRival()".

**Comment by appsmehta** [comment]
Commit for #10 updated 

https://github.com/appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin/commit/530fb0a3cf4d4cb561c2287c374865df145ef3bc

**Comment by vjzaveri** [comment]
@appsmehta 
I think we should make a class named "Team" extending actor, and the other two, captain and teammates will extend Team, doing this we will be properly able to create two teams (making two objects of teams, and then two captains extending their respective teams) as well as inheritance will be proper.

**Comment by ghost** [comment]
Making captain as a subclass of player class is a better option. We can
inherit all the basic properties of player class into captain class while
keeping the unique properties of captain related to toss, inserting input
to circuit, checking output etc separate from other teammates.
Teammates can be another subclass of player class.

Player Class --> {Captain Class}{Teammate Class}
