### ISSUE TITLE
GreenFoot World and Actor Design

### ISSUE THREAD

**Issue by appsmehta** [appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin#4]
Guys, As agreed on the activity, we'll implement Peruvian FlipCoin in GreenFoot. 

For starters, I need help with finalizing our Actors and World model so that the coding work can be assigned for sprint2.

**Comment by appsmehta** [comment]
@yugalk14 , here is a list of actors for which we can start gathering images. 

https://github.com/appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin/blob/master/Greenfoot%20World%20and%20Actors.jpg

**Comment by yugalk14** [comment]
In progress
