### ISSUE TITLE
Create a submission PDF

### ISSUE THREAD

**Issue by yugalk14** [appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin#5]
Submission PDF should include below details:

Team Name (as declared on Canvas)
Names of each Team Member (with CMPE 202 Section Number)
IDs of teach Team Members GitHub account.
Link to Team's GitHub Repository.  Note: Team members are expected to make weekly commits.
Link to Team's Task Board.  Note: All Backlog Items "In Progress" must be assigned to a team member.
Link to Teams Kanban CFD Google Sheet.
Journal Entries from all team members (one page per team member)
This should be a consolidation of individual work from each team member

**Comment by pavanshah77** [comment]
Project pdf has been submitted.
