### ISSUE TITLE
Designing Cryptographic circuit

### ISSUE THREAD

**Issue by vjzaveri** [appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin#7]
Design a 6 level circuit containing combinations of AND and OR gates with 6 digit binary inputs and 6 digit binary output.

**Comment by parvezpatel30** [comment]
Creating a draft function for circuit behavior.

**Comment by parvezpatel30** [comment]
@pavanshah77 Hey Pavan, Is the circuit ready?

**Comment by vjzaveri** [comment]
There are some issues he is facing with the circuit building, we will have to meet up and discuss this in our next meeting.

**Comment by ghost** [comment]
There is an issue with the circuit design that we decided earlier. We may have to make changes in the core design of the circuit. Let's meet so that I can propose those changes before providing the final design.
