### ISSUE TITLE
Writing JUnit test cases for the Cryptographic Circuit

### ISSUE THREAD

**Issue by parvezpatel30** [appsmehta/CMPE202-CSUnplugged-PeruvianFlipCoin#9]
Dependent on #7

**Comment by vjzaveri** [comment]
The circuit diagram uploaded by @pavanshah77 on github is still not the final one and we still need to work on it, so I will have to wait till we finalize the circuit design.

**Comment by ghost** [comment]
I have uploaded the final circuit java module in developer branch. You can start working on JUnit test cases.

**Comment by vjzaveri** [comment]
@pavanshah77 , please provide the input binary and output binary table for the test cases.
